# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: udpa/annotations/security.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'udpa/annotations/security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from udpa.annotations import status_pb2 as udpa_dot_annotations_dot_status__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fudpa/annotations/security.proto\x12\x10udpa.annotations\x1a\x1dudpa/annotations/status.proto\x1a google/protobuf/descriptor.proto\"\xaf\x01\n\x17\x46ieldSecurityAnnotation\x12K\n\"configure_for_untrusted_downstream\x18\x01 \x01(\x08R\x1f\x63onfigureForUntrustedDownstream\x12G\n configure_for_untrusted_upstream\x18\x02 \x01(\x08R\x1d\x63onfigureForUntrustedUpstream:g\n\x08security\x12\x1d.google.protobuf.FieldOptions\x18\xb1\xf2\xa6\x05 \x01(\x0b\x32).udpa.annotations.FieldSecurityAnnotationR\x08securityB\xb7\x01\n\x14\x63om.udpa.annotationsB\rSecurityProtoP\x01Z\'github.com/cncf/xds/go/udpa/annotations\xa2\x02\x03UAX\xaa\x02\x10Udpa.Annotations\xca\x02\x10Udpa\\Annotations\xe2\x02\x1cUdpa\\Annotations\\GPBMetadata\xea\x02\x11Udpa::Annotations\xba\x80\xc8\xd1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udpa.annotations.security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.udpa.annotationsB\rSecurityProtoP\001Z\'github.com/cncf/xds/go/udpa/annotations\242\002\003UAX\252\002\020Udpa.Annotations\312\002\020Udpa\\Annotations\342\002\034Udpa\\Annotations\\GPBMetadata\352\002\021Udpa::Annotations\272\200\310\321\006\002\010\001'
  _globals['_FIELDSECURITYANNOTATION']._serialized_start=119
  _globals['_FIELDSECURITYANNOTATION']._serialized_end=294
# @@protoc_insertion_point(module_scope)
