# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xds/service/orca/v3/orca.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'xds/service/orca/v3/orca.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xds.data.orca.v3 import orca_load_report_pb2 as xds_dot_data_dot_orca_dot_v3_dot_orca__load__report__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1exds/service/orca/v3/orca.proto\x12\x13xds.service.orca.v3\x1a\'xds/data/orca/v3/orca_load_report.proto\x1a\x1egoogle/protobuf/duration.proto\"\x89\x01\n\x15OrcaLoadReportRequest\x12\x42\n\x0freport_interval\x18\x01 \x01(\x0b\x32\x19.google.protobuf.DurationR\x0ereportInterval\x12,\n\x12request_cost_names\x18\x02 \x03(\tR\x10requestCostNames2u\n\x0eOpenRcaService\x12\x63\n\x11StreamCoreMetrics\x12*.xds.service.orca.v3.OrcaLoadReportRequest\x1a .xds.data.orca.v3.OrcaLoadReport0\x01\x42\xc6\x01\n\x17\x63om.xds.service.orca.v3B\tOrcaProtoP\x01Z1github.com/cncf/xds/go/xds/service/orca/v3;orcav3\xa2\x02\x03XSO\xaa\x02\x13Xds.Service.Orca.V3\xca\x02\x13Xds\\Service\\Orca\\V3\xe2\x02\x1fXds\\Service\\Orca\\V3\\GPBMetadata\xea\x02\x16Xds::Service::Orca::V3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xds.service.orca.v3.orca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.xds.service.orca.v3B\tOrcaProtoP\001Z1github.com/cncf/xds/go/xds/service/orca/v3;orcav3\242\002\003XSO\252\002\023Xds.Service.Orca.V3\312\002\023Xds\\Service\\Orca\\V3\342\002\037Xds\\Service\\Orca\\V3\\GPBMetadata\352\002\026Xds::Service::Orca::V3'
  _globals['_ORCALOADREPORTREQUEST']._serialized_start=129
  _globals['_ORCALOADREPORTREQUEST']._serialized_end=266
  _globals['_OPENRCASERVICE']._serialized_start=268
  _globals['_OPENRCASERVICE']._serialized_end=385
# @@protoc_insertion_point(module_scope)
