# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xds/annotations/v3/migrate.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'xds/annotations/v3/migrate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n xds/annotations/v3/migrate.proto\x12\x12xds.annotations.v3\x1a google/protobuf/descriptor.proto\"+\n\x11MigrateAnnotation\x12\x16\n\x06rename\x18\x01 \x01(\tR\x06rename\"Y\n\x16\x46ieldMigrateAnnotation\x12\x16\n\x06rename\x18\x01 \x01(\tR\x06rename\x12\'\n\x0foneof_promotion\x18\x02 \x01(\tR\x0eoneofPromotion\"?\n\x15\x46ileMigrateAnnotation\x12&\n\x0fmove_to_package\x18\x02 \x01(\tR\rmoveToPackage:r\n\x0fmessage_migrate\x12\x1f.google.protobuf.MessageOptions\x18\xce\xe9\xed\x35 \x01(\x0b\x32%.xds.annotations.v3.MigrateAnnotationR\x0emessageMigrate:q\n\rfield_migrate\x12\x1d.google.protobuf.FieldOptions\x18\xce\xe9\xed\x35 \x01(\x0b\x32*.xds.annotations.v3.FieldMigrateAnnotationR\x0c\x66ieldMigrate:i\n\x0c\x65num_migrate\x12\x1c.google.protobuf.EnumOptions\x18\xce\xe9\xed\x35 \x01(\x0b\x32%.xds.annotations.v3.MigrateAnnotationR\x0b\x65numMigrate:y\n\x12\x65num_value_migrate\x12!.google.protobuf.EnumValueOptions\x18\xce\xe9\xed\x35 \x01(\x0b\x32%.xds.annotations.v3.MigrateAnnotationR\x10\x65numValueMigrate:m\n\x0c\x66ile_migrate\x12\x1c.google.protobuf.FileOptions\x18\xce\xe9\xed\x35 \x01(\x0b\x32).xds.annotations.v3.FileMigrateAnnotationR\x0b\x66ileMigrateB\xc9\x01\n\x16\x63om.xds.annotations.v3B\x0cMigrateProtoP\x01Z7github.com/cncf/xds/go/xds/annotations/v3;annotationsv3\xa2\x02\x03XAX\xaa\x02\x12Xds.Annotations.V3\xca\x02\x12Xds\\Annotations\\V3\xe2\x02\x1eXds\\Annotations\\V3\\GPBMetadata\xea\x02\x14Xds::Annotations::V3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xds.annotations.v3.migrate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.xds.annotations.v3B\014MigrateProtoP\001Z7github.com/cncf/xds/go/xds/annotations/v3;annotationsv3\242\002\003XAX\252\002\022Xds.Annotations.V3\312\002\022Xds\\Annotations\\V3\342\002\036Xds\\Annotations\\V3\\GPBMetadata\352\002\024Xds::Annotations::V3'
  _globals['_MIGRATEANNOTATION']._serialized_start=90
  _globals['_MIGRATEANNOTATION']._serialized_end=133
  _globals['_FIELDMIGRATEANNOTATION']._serialized_start=135
  _globals['_FIELDMIGRATEANNOTATION']._serialized_end=224
  _globals['_FILEMIGRATEANNOTATION']._serialized_start=226
  _globals['_FILEMIGRATEANNOTATION']._serialized_end=289
# @@protoc_insertion_point(module_scope)
