# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xds/annotations/v3/security.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'xds/annotations/v3/security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xds.annotations.v3 import status_pb2 as xds_dot_annotations_dot_v3_dot_status__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!xds/annotations/v3/security.proto\x12\x12xds.annotations.v3\x1a\x1fxds/annotations/v3/status.proto\x1a google/protobuf/descriptor.proto\"\xaf\x01\n\x17\x46ieldSecurityAnnotation\x12K\n\"configure_for_untrusted_downstream\x18\x01 \x01(\x08R\x1f\x63onfigureForUntrustedDownstream\x12G\n configure_for_untrusted_upstream\x18\x02 \x01(\x08R\x1d\x63onfigureForUntrustedUpstream:i\n\x08security\x12\x1d.google.protobuf.FieldOptions\x18\xa7\x96\x9d/ \x01(\x0b\x32+.xds.annotations.v3.FieldSecurityAnnotationR\x08securityB\xd2\x01\n\x16\x63om.xds.annotations.v3B\rSecurityProtoP\x01Z7github.com/cncf/xds/go/xds/annotations/v3;annotationsv3\xa2\x02\x03XAX\xaa\x02\x12Xds.Annotations.V3\xca\x02\x12Xds\\Annotations\\V3\xe2\x02\x1eXds\\Annotations\\V3\\GPBMetadata\xea\x02\x14Xds::Annotations::V3\xd2\xc6\xa4\xe1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xds.annotations.v3.security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.xds.annotations.v3B\rSecurityProtoP\001Z7github.com/cncf/xds/go/xds/annotations/v3;annotationsv3\242\002\003XAX\252\002\022Xds.Annotations.V3\312\002\022Xds\\Annotations\\V3\342\002\036Xds\\Annotations\\V3\\GPBMetadata\352\002\024Xds::Annotations::V3\322\306\244\341\006\002\010\001'
  _globals['_FIELDSECURITYANNOTATION']._serialized_start=125
  _globals['_FIELDSECURITYANNOTATION']._serialized_end=300
# @@protoc_insertion_point(module_scope)
