# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xds/type/matcher/v3/ip.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'xds/type/matcher/v3/ip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from xds.annotations.v3 import status_pb2 as xds_dot_annotations_dot_v3_dot_status__pb2
from xds.core.v3 import cidr_pb2 as xds_dot_core_dot_v3_dot_cidr__pb2
from xds.type.matcher.v3 import matcher_pb2 as xds_dot_type_dot_matcher_dot_v3_dot_matcher__pb2
from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cxds/type/matcher/v3/ip.proto\x12\x13xds.type.matcher.v3\x1a\x1fxds/annotations/v3/status.proto\x1a\x16xds/core/v3/cidr.proto\x1a!xds/type/matcher/v3/matcher.proto\x1a\x1b\x62uf/validate/validate.proto\"\x8d\x02\n\tIPMatcher\x12T\n\x0erange_matchers\x18\x01 \x03(\x0b\x32-.xds.type.matcher.v3.IPMatcher.IPRangeMatcherR\rrangeMatchers\x1a\xa9\x01\n\x0eIPRangeMatcher\x12\x38\n\x06ranges\x18\x01 \x03(\x0b\x32\x16.xds.core.v3.CidrRangeB\x08\xbaH\x05\x92\x01\x02\x08\x01R\x06ranges\x12?\n\x08on_match\x18\x02 \x01(\x0b\x32$.xds.type.matcher.v3.Matcher.OnMatchR\x07onMatch\x12\x1c\n\texclusive\x18\x03 \x01(\x08R\texclusiveB\xcf\x01\n\x17\x63om.xds.type.matcher.v3B\x07IpProtoP\x01Z4github.com/cncf/xds/go/xds/type/matcher/v3;matcherv3\xa2\x02\x03XTM\xaa\x02\x13Xds.Type.Matcher.V3\xca\x02\x13Xds\\Type\\Matcher\\V3\xe2\x02\x1fXds\\Type\\Matcher\\V3\\GPBMetadata\xea\x02\x16Xds::Type::Matcher::V3\xd2\xc6\xa4\xe1\x06\x02\x08\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xds.type.matcher.v3.ip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027com.xds.type.matcher.v3B\007IpProtoP\001Z4github.com/cncf/xds/go/xds/type/matcher/v3;matcherv3\242\002\003XTM\252\002\023Xds.Type.Matcher.V3\312\002\023Xds\\Type\\Matcher\\V3\342\002\037Xds\\Type\\Matcher\\V3\\GPBMetadata\352\002\026Xds::Type::Matcher::V3\322\306\244\341\006\002\010\001'
  _globals['_IPMATCHER_IPRANGEMATCHER'].fields_by_name['ranges']._loaded_options = None
  _globals['_IPMATCHER_IPRANGEMATCHER'].fields_by_name['ranges']._serialized_options = b'\272H\005\222\001\002\010\001'
  _globals['_IPMATCHER']._serialized_start=175
  _globals['_IPMATCHER']._serialized_end=444
  _globals['_IPMATCHER_IPRANGEMATCHER']._serialized_start=275
  _globals['_IPMATCHER_IPRANGEMATCHER']._serialized_end=444
# @@protoc_insertion_point(module_scope)
