#!/bin/bash
# Buf protobuf generation script
# Replaces the Bazel-based proto generation for Go and Python

set -e

echo "Generating protobuf files using Buf with separate configs per language..."

# Ensure buf is available
if ! command -v buf &> /dev/null; then
    echo "Error: buf CLI not found. Please install buf: https://docs.buf.build/installation"
    exit 1
fi

# Update dependencies
echo "Updating Buf dependencies..."
buf dep update

# Generate Go protobuf files
echo "Generating Go protobuf files (including UDPA)..."
buf generate --template buf.gen.go.yaml

# Generate Python protobuf files (with validation support)
echo "Generating Python protobuf files (including UDPA and validation)..."
buf generate --template buf.gen.python.yaml

# Setup Python package structure
echo "Setting up Python package structure..."
find python -type d | while read dir; do
    if [ ! -f "$dir/__init__.py" ]; then
        touch "$dir/__init__.py"
        echo "Created $dir/__init__.py"
    fi
done

echo "Protobuf generation completed successfully!"
echo ""
echo "Generated files:"
echo "  Go:     $(find go -name "*.go" | wc -l) files in go/ (includes XDS and UDPA)"
echo "  Python: $(find python -name "*.py" | wc -l) files in python/ (includes XDS and UDPA)"
echo ""
echo "Includes:"
echo "  - Standard protobuf files (.pb.go, _pb2.py)"
echo "  - gRPC service files (_grpc.pb.go)"
echo "  - Go validation files (.pb.validate.go via remote protoc-gen-validate plugin)"
echo "  - Python validation files (validate_pb2.py generated by buf)"
echo "  - UDPA protobuf files (both XDS and UDPA packages)"
echo ""
echo "Note: Using separate buf.gen configs per language for clean separation"
echo "Module: buf.build/cncf/xds"