#!/bin/bash
# Buf protobuf generation script
# Replaces the Bazel-based proto generation for Go and Python

set -e

echo "Generating protobuf files using Buf..."

# Ensure buf is available
if ! command -v buf &> /dev/null; then
    echo "Error: buf CLI not found. Please install buf: https://docs.buf.build/installation"
    exit 1
fi

# Ensure protoc-gen-validate is available for Go validation generation
if ! command -v protoc-gen-validate &> /dev/null; then
    echo "protoc-gen-validate not found in PATH. Installing..."
    go install github.com/envoyproxy/protoc-gen-validate@v1.0.4
fi

# Add Go bin to PATH for local plugins
export PATH="$HOME/go/bin:$PATH"

# Update dependencies
echo "Updating Buf dependencies..."
buf dep update

# Generate protobuf files
echo "Generating Go and Python protobuf files (including UDPA)..."
buf generate

# Remove unwanted Go files from validate.proto dependency
# (These are generated by buf from the dependency, but Go validation should come from the official plugin)
if [ -d "go/validate" ]; then
    echo "Removing unwanted Go validate files from dependency (keeping official plugin-generated validation)..."
    rm -rf go/validate
fi

# Setup Python package structure
echo "Setting up Python package structure..."
find python -type d | while read dir; do
    if [ ! -f "$dir/__init__.py" ]; then
        touch "$dir/__init__.py"
        echo "Created $dir/__init__.py"
    fi
done

echo "Protobuf generation completed successfully!"
echo ""
echo "Generated files:"
echo "  Go:     $(find go -name "*.go" | wc -l) files in go/ (includes XDS and UDPA)"
echo "  Python: $(find python -name "*.py" | wc -l) files in python/ (includes XDS and UDPA)"
echo ""
echo "Includes:"
echo "  - Standard protobuf files (.pb.go, _pb2.py)"
echo "  - gRPC service files (_grpc.pb.go)"
echo "  - Go validation files (.pb.validate.go via official protoc-gen-validate plugin)"
echo "  - Python validation files (validate_pb2.py generated by buf)"
echo "  - UDPA protobuf files (both XDS and UDPA packages)"
echo ""
echo "Note: Unwanted go/validate/ files from dependencies are automatically removed"
echo "Module: buf.build/cncf/xds"