load("//bazel:xds_proto_package.bzl", "xds_proto_package")

licenses(["notice"])  # Apache 2

xds_proto_package(
    deps = [
        "//xds/annotations/v3:pkg",
        "//xds/core/v3:pkg",
        "//xds/type/v3:pkg",
    ],
)
