name: Publish to BCR

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to Bazel Central Registry
    permissions:
      contents: write
      id-token: write
      attestations: write
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@v1
    with:
      tag_name: ${{ github.ref_name }}
      # Fork bazelbuild/bazel-central-registry and update this to your fork
      registry_fork: cncf/bazel-central-registry
      draft: false
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}

